# Generated by Django 4.1.13 on 2024-01-29 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("MashleAPI", "0002_menuitems_stock_table_reviews_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="number",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="table",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
