# Generated by Django 4.1.13 on 2024-01-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MashleAPI", "0003_alter_table_number_alter_table_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="user",
        ),
        migrations.AlterField(
            model_name="reservation",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.TimeField(auto_now_add=True),
        ),
    ]
