# Generated by Django 4.1.13 on 2024-01-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MashleAPI', '0006_alter_category_title_alter_menuitems_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
    ]
