# Generated by Django 4.1.13 on 2024-01-31 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("MashleAPI", "0007_alter_menuitems_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="menuitem",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="MashleAPI.menuitems",
            ),
            preserve_default=False,
        ),
    ]
