# Generated by Django 4.1.13 on 2024-03-21 02:43

import MashleAPI.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("MashleAPI", "0008_reviews_menuitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitems",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now,
                upload_to=MashleAPI.models.generate_filename,
            ),
            preserve_default=False,
        ),
    ]
