# Generated by Django 4.1.13 on 2024-01-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Mashle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
