# Generated by Django 4.1.13 on 2024-01-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Mashle", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitems",
            name="subtotal",
        ),
        migrations.AddField(
            model_name="cartitems",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cartitems",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
