# Generated by Django 4.1.13 on 2024-01-25 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Mashle", "0002_remove_cartitems_subtotal_cartitems_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitems",
            name="price",
        ),
    ]
