# Generated by Django 4.1.13 on 2024-01-27 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Mashle", "0002_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitems",
            name="menuitem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Mashle.menuitems",
                verbose_name="Menu Item",
            ),
        ),
        migrations.AlterField(
            model_name="orderitems",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Mashle.order",
                verbose_name="Order",
            ),
        ),
    ]
