# Generated by Django 4.1.13 on 2024-01-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Mashle", "0003_remove_cartitems_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitems",
            name="price",
            field=models.DecimalField(decimal_places=2, default=60, max_digits=10),
            preserve_default=False,
        ),
    ]
